### PR TITLE
Add spaces between values and units

### PR DESCRIPTION
**Pull request by SerVB**
Punctuation of units is improved. Now values are more readable because of an extra space between the value and the unit. By the way, it's the SI standard:
* https://english.stackexchange.com/questions/2794/punctuation-with-units
* https://www.bipm.org/en/publications/si-brochure/section5-3.html

### CODE REVIEW

**Comment by raiguard** [comment]
Makes sense to me.

**Comment by SerVB** [comment]
@raiguard In the SI standard (the second web page), there is also a rule says that percent (%) sign must be spaced. I can do this. What do you think?

**Comment by raiguard** [comment]
I’ve always written % without a space, and that is what I see 99% of the Rainmeter community do it. So I think we should leave that as-is.

Plus, I think it looks better.

**Comment by SerVB** [comment]
OK.

**Pull request merged**
