### PR TITLE
Add "view global settings" button

### PR DESCRIPTION
**Pull request by SerVB**
I'm starting to implement #71. Is it OK? Please, check this out.

### CODE REVIEW

**Comment by SerVB** [comment]
I've added the "(view file)" button:
image
A click here opens the `#@#Settings\GlobalSettings.inc` file. There is no design at all...

**Comment by SerVB** [comment]
Maybe I should add `ToolTipText="view settings file"` to styles.
Also the style name `StyleGlobalSettingsFileButton` have to be changed to something like `StyleGoToSettingsFileButton` because it will be a common style.

**Comment by SerVB** [comment]
Design updated to something mentioned in #71.

**Comment by raiguard** [comment]
Sorry, I've been terribly busy. Merged.

**Pull request merged**
