### PR TITLE
Automated generation of Disks.ini

### PR DESCRIPTION
**Pull request by Zer0t3ch**
Currently untested, but should have no issues. 

See [this Reddit comment](https://www.reddit.com/r/gadgets/comments/8oyi8z/amd_reveals_threadripper_2_32_core_cpu_for_high/e09ks14/?context=999) for further details.

### CODE REVIEW

**Comment by raiguard** [comment]
Moving the discussion here to make things easier (Reddit comments aren't the best platform for this kind of thing).

There are several issues with the way the output INI is structured. Everything in Rainmeter is loaded top-down, meaning that measures and meters written in the file will be read and applied in the order they were written in. This means that your idea of putting all of the measures and meters after the rest of the config sections won't work. This is what the output looks like when written into the skin:



Whereas it is supposed to look like this:



So as you can see, order is very important.

I think I miscommunicated what I actually wanted from the script. My idea is that I would put a single template into a source file (the disk measures, disk meters, line color / measure name, etc.) and would retrieve the output for that specific section and paste it into my Disks.ini file. This way it saves you a lot of extra work, and only adds a bit of work for me. This is already going to save me tons of time so I don't need it to be one-click-fits-all, if you know what I mean.

Does that make sense? I'm not good at explaining my ideas in words so I'm not sure if I communicated that effectively...

**Comment by raiguard** [comment]
I just realized: My problem could also be solved by simply not adding the generated text to a preexisting file. Separate the meter and measure sections into two templates (so it will do all of the measures in a row, then all of the meters in a row), then I could just copy/paste the sections I need into Disks.ini by hand. That saves you a ton of headaches (it's a fairly minor change), and basically solves all of my problems.

There are just a few more things that don't work correctly: You assumed that changing `LineColor` and `MeasureName` in the line graph to `LineColor1` and `MeasureName1` would work. This, in fact, does not work. The first options in Rainmeter always start without a number, then additionally added ones have numbers starting from 2. I can simply delete the 1's, but I thought I would let you know.

A final thing: In the output file, the line color and measure name generated outputs are combined into single lines. See below:

`[GraphLines]
Meter=Line
MeterStyle=StyleLineGraph
X=r
Y=r
W=(#graphWidth# - 2)
H=(#graphHeight# - 2)
LineCount=26
DynamicVariables=1
Antialias=#lineGraphAa#
AutoScale=1
Hidden=(#showLineGraph# = 0)
Group=LineGraph
MeasureName=MeasureDiskAActivity
LineColor=#colorDiskA#,((#hideDiskA# = 1) ? 0 : 255)MeasureName2=MeasureDiskBActivity
LineColor2=#colorDiskB#,((#hideDiskB# = 1) ? 0 : 255)MeasureName3=MeasureDiskCActivity
LineColor3=#colorDiskC#,((#hideDiskC# = 1) ? 0 : 255)MeasureName4=MeasureDiskDActivity
LineColor4=#colorDiskD#,((#hideDiskD# = 1) ? 0 : 255)MeasureName5=MeasureDiskEActivity
LineColor5=#colorDiskE#,((#hideDiskE# = 1) ? 0 : 255)MeasureName6=MeasureDiskFActivity
LineColor6=#colorDiskF#,((#hideDiskF# = 1) ? 0 : 255)MeasureName7=MeasureDiskGActivity
LineColor7=#colorDiskG#,((#hideDiskG# = 1) ? 0 : 255)MeasureName8=MeasureDiskHActivity
LineColor8=#colorDiskH#,((#hideDiskH# = 1) ? 0 : 255)MeasureName9=MeasureDiskIActivity
LineColor9=#colorDiskI#,((#hideDiskI# = 1) ? 0 : 255)MeasureName10=MeasureDiskJActivity
LineColor10=#colorDiskJ#,((#hideDiskJ# = 1) ? 0 : 255)MeasureName11=MeasureDiskKActivity
LineColor11=#colorDiskK#,((#hideDiskK# = 1) ? 0 : 255)MeasureName12=MeasureDiskLActivity
LineColor12=#colorDiskL#,((#hideDiskL# = 1) ? 0 : 255)MeasureName13=MeasureDiskMActivity
LineColor13=#colorDiskM#,((#hideDiskM# = 1) ? 0 : 255)MeasureName14=MeasureDiskNActivity
LineColor14=#colorDiskN#,((#hideDiskN# = 1) ? 0 : 255)MeasureName15=MeasureDiskOActivity
LineColor15=#colorDiskO#,((#hideDiskO# = 1) ? 0 : 255)MeasureName16=MeasureDiskPActivity
LineColor16=#colorDiskP#,((#hideDiskP# = 1) ? 0 : 255)MeasureName17=MeasureDiskQActivity
LineColor17=#colorDiskQ#,((#hideDiskQ# = 1) ? 0 : 255)MeasureName18=MeasureDiskRActivity
LineColor18=#colorDiskR#,((#hideDiskR# = 1) ? 0 : 255)MeasureName19=MeasureDiskSActivity
LineColor19=#colorDiskS#,((#hideDiskS# = 1) ? 0 : 255)MeasureName20=MeasureDiskTActivity
LineColor20=#colorDiskT#,((#hideDiskT# = 1) ? 0 : 255)MeasureName21=MeasureDiskUActivity
LineColor21=#colorDiskU#,((#hideDiskU# = 1) ? 0 : 255)MeasureName22=MeasureDiskVActivity
LineColor22=#colorDiskV#,((#hideDiskV# = 1) ? 0 : 255)MeasureName23=MeasureDiskWActivity
LineColor23=#colorDiskW#,((#hideDiskW# = 1) ? 0 : 255)MeasureName24=MeasureDiskXActivity
LineColor24=#colorDiskX#,((#hideDiskX# = 1) ? 0 : 255)MeasureName25=MeasureDiskYActivity
LineColor25=#colorDiskY#,((#hideDiskY# = 1) ? 0 : 255)MeasureName26=MeasureDiskZActivity
LineColor26=#colorDiskZ#,((#hideDiskZ# = 1) ? 0 : 255)`

Whereas this is what it is supposed to look like:

`[GraphLines]
Meter=Line
MeterStyle=StyleLineGraph
X=r
Y=r
W=(#graphWidth# - 2)
H=(#graphHeight# - 2)
LineCount=26
MeasureName=MeasureDiskZActivity
MeasureName2=MeasureDiskYActivity
MeasureName3=MeasureDiskXActivity
MeasureName4=MeasureDiskWActivity
MeasureName5=MeasureDiskVActivity
MeasureName6=MeasureDiskUActivity
MeasureName7=MeasureDiskTActivity
MeasureName8=MeasureDiskSActivity
MeasureName9=MeasureDiskRActivity
MeasureName10=MeasureDiskQActivity
MeasureName11=MeasureDiskPActivity
MeasureName12=MeasureDiskOActivity
MeasureName13=MeasureDiskNActivity
MeasureName14=MeasureDiskMActivity
MeasureName15=MeasureDiskLActivity
MeasureName16=MeasureDiskKActivity
MeasureName17=MeasureDiskJActivity
MeasureName18=MeasureDiskIActivity
MeasureName19=MeasureDiskHActivity
MeasureName20=MeasureDiskGActivity
MeasureName21=MeasureDiskFActivity
MeasureName22=MeasureDiskEActivity
MeasureName23=MeasureDiskDActivity
MeasureName24=MeasureDiskCActivity
MeasureName25=MeasureDiskBActivity
MeasureName26=MeasureDiskAActivity
LineColor=#colorDiskZ#,((#hideDiskZ# = 1) ? 0 : 255)
LineColor2=#colorDiskY#,((#hideDiskY# = 1) ? 0 : 255)
LineColor3=#colorDiskX#,((#hideDiskX# = 1) ? 0 : 255)
LineColor4=#colorDiskW#,((#hideDiskW# = 1) ? 0 : 255)
LineColor5=#colorDiskV#,((#hideDiskV# = 1) ? 0 : 255)
LineColor6=#colorDiskU#,((#hideDiskU# = 1) ? 0 : 255)
LineColor7=#colorDiskT#,((#hideDiskT# = 1) ? 0 : 255)
LineColor8=#colorDiskS#,((#hideDiskS# = 1) ? 0 : 255)
LineColor9=#colorDiskR#,((#hideDiskR# = 1) ? 0 : 255)
LineColor10=#colorDiskQ#,((#hideDiskQ# = 1) ? 0 : 255)
LineColor11=#colorDiskP#,((#hideDiskP# = 1) ? 0 : 255)
LineColor12=#colorDiskO#,((#hideDiskO# = 1) ? 0 : 255)
LineColor13=#colorDiskN#,((#hideDiskN# = 1) ? 0 : 255)
LineColor14=#colorDiskM#,((#hideDiskM# = 1) ? 0 : 255)
LineColor15=#colorDiskL#,((#hideDiskL# = 1) ? 0 : 255)
LineColor16=#colorDiskK#,((#hideDiskK# = 1) ? 0 : 255)
LineColor17=#colorDiskJ#,((#hideDiskJ# = 1) ? 0 : 255)
LineColor18=#colorDiskI#,((#hideDiskI# = 1) ? 0 : 255)
LineColor19=#colorDiskH#,((#hideDiskH# = 1) ? 0 : 255)
LineColor20=#colorDiskG#,((#hideDiskG# = 1) ? 0 : 255)
LineColor21=#colorDiskF#,((#hideDiskF# = 1) ? 0 : 255)
LineColor22=#colorDiskE#,((#hideDiskE# = 1) ? 0 : 255)
LineColor23=#colorDiskD#,((#hideDiskD# = 1) ? 0 : 255)
LineColor24=#colorDiskC#,((#hideDiskC# = 1) ? 0 : 255)
LineColor25=#colorDiskB#,((#hideDiskB# = 1) ? 0 : 255)
LineColor26=#colorDiskA#,((#hideDiskA# = 1) ? 0 : 255)
DynamicVariables=1
Antialias=#lineGraphAa#
AutoScale=1
Hidden=(#showLineGraph# = 0)
Group=LineGraph`

So separating the LineColor and MeasureName templates would be beneficial as well.

**Comment by raiguard** [comment]
There is another problem I just noticed with the line graph specifically: The graph generated by your script has the disk letters going in alphabetical order. For the histograms and line graph, they actually need to be in reverse alphabetical order. This is so that the histogram and line graph for Disk A will be "in front" of the other lines (remember what I said about everything in Rainmeter being loaded in sequential order from the top down?).

**Comment by raiguard** [comment]
Just so you know, you don't have to do this for me. I have an idea of how I could do it myself using Rainmeter and LUA, but I opted to go with your method because simply running a batch file is much easier to use than having to open a Rainmeter skin and interact with it that way. So if this becomes too much of a headache for you, that's fine. Thanks for your help!

**Comment by raiguard** [comment]
So, thanks for your work, but I ended up writing my own using LUA and Rainmeter. It gives me a ton more options that probably wouldn't have been possible through a batch script. Thanks for your help, and thank you for giving me the idea (seriously, it's already saved me so much time. I updated CPU Meter to support 64 threads in about two seconds).

**Comment by Zer0t3ch** [comment]
I'm glad I could help. I actually meant to come back and tweak the script for you, but I completely forgot. 

Do yourself a favor though: anything you bother scripting, get the copy-pasting out of your workflow. Whatever you end up generating is (comparatively to generating) very easy to do the equivalent of pasting wherever it needs to go. My work was shoddy because I didn't know much about what I was working with, but my overall intent should be relatively easy to replicate without excessive copy-pasting.

Best of luck on the project.

**Comment by raiguard** [comment]
Thanks, I'll need it!

I'm still punching my keyboard thinking about all the time I didn't need to spend... Ugh. But now it's better so life is good!

**Pull request closed without merging**
